/**
 * A program for planning trips on the City of London's public transit system,
 * complete with expected trip times and instructions for changing train lines
 * to achieve the quickest possible trip between two stations.
 * 
 * Stations accepted as valid start and end points include all stations
 * directly served by any of rail lines operated by Transport for London, as
 * of May 2018. This includes the 11 London Underground subway lines, as well 
 * as the Docklands Light Railway (DLR), London Overground, TfL Rail, and 
 * Tramlink light rail lines. A list of valid stations, in alphabetical order, 
 * is provided in the file stationlist.txt for reference. 
 * 
 * The user input to the program should be in the following format.
 * 
 * <start_station> TO <destination_station>
 * <start_station> TO <destination_station>
 * etc.
 * 
 * A sample input file to the program (exampleinput.txt) is provided.
 * 
 * For each pair of stations provided in the input file, the program will print
 * directions for traveling from the start station to the destination in the
 * least expected amount of time, using data on the frequency of train arrivals
 * for each line and station, and the expected transit time between adjacent 
 * stations.
 * 
 * Directions given assume that all train lines are open and operating for the 
 * duration of the commuter's trip, and the expected transit times shown assume
 * the commuter is travelling during off-peak hours.
 */

#ifndef TUBEPLANNER_H
#define TUBEPLANNER_H

/* INCLUDE STATEMENTS */
#include <algorithm>
#include <deque>
#include <iostream>
#include <iterator>
#include <limits>
#include <sstream>
#include <string>
#include <unordered_map>
#include <vector>

/* USING DECLARATIONS */
using StationLineIDsMap = std::unordered_map< std::string,std::unordered_map<std::string,int> >;

/* DATA TYPE DEFINITIONS */

/*
 * This struct defines a train line segment link between two stations, 
 * specifying the names of the two stations, the train line the connection is
 * on, the expected transit time, as well as whether or not the connection is
 * symmetric between the two stations.
 * 
 * An is_symmetric value of false indicates the (rare) case of a strictly 
 * one-way train connection between two stations on this line.
 */
struct TrainConnection {
    std::string line;           /* Train line that this connection is a part of */
    std::string from_station;   /* Starting station of this connection */
    std::string to_station;     /* Ending station of this connection */
    int travel_time;            /* Expected travel time between the two stations */
    bool is_symmetric;          /* Whether or not the connection is symmetric */
};

/*
 * For stations that are interchange stations between multiple train lines,
 * we specify the station name, the two train lines and the transfer time
 * between them (i.e. the expected amount of time the user will need to spend
 * in the station before getting on the next destination line train) for each
 * possible transfer between train lines at that station.
 * 
 * We will assign the transfer time to be the frequency at which
 * trains on the destination line arrive at the station (e.g. every 5 minutes). 
 * (The instances in which a commuter catches and misses the next train while 
 * moving between platforms shall be assumed to average out.)
 * 
 * Note that all interchanges are defined asymmetrically.
 */
struct Interchange {
    std::string from_station;   /* Name of the station at the start of the interchange */
    std::string from_line;      /* Line the commuter is transferring from */
    std::string to_station;     /* Name of the station at the end of the interchange */
    std::string to_line;        /* Line the commuter is transferring to */
    int transfer_time;          /* Time to transfer lines, in minutes */
};

/*
 * A graph edge representing a connection (via train line or interchange) to
 * a particular destination station. The edge is stored in the adjacency list
 * of the starting station's graph vertex.
 */
struct StationEdge {
    int to_id;        /* ID of the destination station */
    int time_taken;   /* Time it takes to get to the end station */
};

/* 
 * A vertex for the graph, representing a station on the Tube Map. A station
 * with multiple train lines departing from or arriving to it is treated as
 * multiple separate stations (one for each line) for the purposes of 
 * constucting the graph. Each StationVertex stores an adjacency list of 
 * (directed) edges connecting to other stations in the graph.
 */
struct StationVertex {
    int id;                          /* Unique numerical ID for this station */
    std::string name;                /* Name of the station */
    std::string line;                /* Train line this station is on */
    std::vector<StationEdge> edges;  /* Adjacency list of connected stations */
};


/* FUNCTION DECLARATIONS */
void read_in_train_connections (std::vector<StationVertex>& station_vertices, 
        StationLineIDsMap& station_line_ids);

void read_in_interchanges (std::vector<StationVertex>& station_vertices,
        const StationLineIDsMap& station_line_ids);

std::deque<int> get_fastest_route (const std::vector<StationVertex>& station_vertices,
        const StationLineIDsMap& station_line_ids, const std::string& from_station, 
        const std::string& to_station);

void print_directions (const std::vector<StationVertex>& station_vertices,
        const std::deque<int>& station_path);

int get_travel_time (const std::vector<StationVertex>& station_vertices,
        int start_id, int end_id);

/* GLOBAL VARIABLE INITIALIZATIONS */

const std::vector<TrainConnection> train_connections = {
    /* Adjacent stations on the Bakerloo Line */
    {"Bakerloo", "Harrow & Wealdstone", "Kenton", 3, true},
    {"Bakerloo", "Kenton", "South Kenton", 2, true},
    {"Bakerloo", "South Kenton", "North Wembley", 2, true},
    {"Bakerloo", "North Wembley", "Wembley Central", 2, true},
    {"Bakerloo", "Wembley Central", "Stonebridge Park", 3, true},
    {"Bakerloo", "Stonebridge Park", "Harlesden", 2, true},
    {"Bakerloo", "Harlesden", "Willesden Junction", 2, true},
    {"Bakerloo", "Willesden Junction", "Kensal Green", 3, true},
    {"Bakerloo", "Kensal Green", "Queen's Park", 3, true},
    {"Bakerloo", "Queen's Park", "Kilburn Park", 3, true},
    {"Bakerloo", "Kilburn Park", "Maida Vale", 2, true},
    {"Bakerloo", "Maida Vale", "Warwick Avenue", 2, true},
    {"Bakerloo", "Warwick Avenue", "Paddington", 2, true},
    {"Bakerloo", "Paddington", "Edgware Road (Bakerloo)", 2, true},
    {"Bakerloo", "Edgware Road (Bakerloo)", "Marylebone", 1, true},
    {"Bakerloo", "Marylebone", "Baker Street", 1, true},
    {"Bakerloo", "Baker Street", "Regent's Park", 2, true},
    {"Bakerloo", "Regent's Park", "Oxford Circus", 2, true},
    {"Bakerloo", "Oxford Circus", "Piccadilly Circus", 2, true},
    {"Bakerloo", "Piccadilly Circus", "Charing Cross", 2, true},
    {"Bakerloo", "Charing Cross", "Embankment", 1, true},
    {"Bakerloo", "Embankment", "Waterloo", 1, true},
    {"Bakerloo", "Waterloo", "Lambeth North", 2, true},
    {"Bakerloo", "Lambeth North", "Elephant & Castle", 2, true},

    /* Adjacent stations on the Central Line */
    {"Central", "Epping", "Theydon Bois", 3, true},
    {"Central", "Theydon Bois", "Debden", 3, true},
    {"Central", "Debden", "Loughton", 3, true},
    {"Central", "Loughton", "Buckhurst Hill", 3, true},
    {"Central", "Buckhurst Hill", "Woodford", 2, true},
    {"Central", "Woodford", "Roding Valley", 2, true},
    {"Central", "Roding Valley", "Chigwell", 3, true},
    {"Central", "Chigwell", "Grange Hill", 2, true},
    {"Central", "Grange Hill", "Hainault", 3, true},
    {"Central", "Hainault", "Fairlop", 2, true},
    {"Central", "Fairlop", "Barkingside", 2, true},
    {"Central", "Barkingside", "Newbury Park", 2, true},
    {"Central", "Newbury Park", "Gants Hill", 3, true},
    {"Central", "Gants Hill", "Redbridge", 2, true},
    {"Central", "Redbridge", "Wanstead", 2, true},
    {"Central", "Wanstead", "Leytonstone", 3, true},
    {"Central", "Woodford", "South Woodford", 3, true},
    {"Central", "South Woodford", "Snaresbrook", 3, true},
    {"Central", "Snaresbrook", "Leytonstone", 3, true},
    {"Central", "Leytonstone", "Leyton", 2, true},
    {"Central", "Leyton", "Stratford", 3, true},
    {"Central", "Stratford", "Mile End", 3, true},
    {"Central", "Mile End", "Bethnal Green (Central)", 3, true},
    {"Central", "Bethnal Green (Central)", "Liverpool Street", 3, true},
    {"Central", "Liverpool Street", "Bank", 2, true},
    {"Central", "Bank", "St Paul's", 2, true},
    {"Central", "St Paul's", "Chancery Lane", 2, true},
    {"Central", "Chancery Lane", "Holborn", 1, true},
    {"Central", "Holborn", "Tottenham Court Road", 2, true},
    {"Central", "Tottenham Court Road", "Oxford Circus", 1, true},
    {"Central", "Oxford Circus", "Bond Street", 2, true},
    {"Central", "Bond Street", "Marble Arch", 1, true},
    {"Central", "Marble Arch", "Lancaster Gate", 2, true},
    {"Central", "Lancaster Gate", "Queensway", 2, true},
    {"Central", "Queensway", "Notting Hill Gate", 2, true},
    {"Central", "Notting Hill Gate", "Holland Park", 1, true},
    {"Central", "Holland Park", "Shepherd's Bush", 2, true},
    {"Central", "Shepherd's Bush", "White City", 4, true},
    {"Central", "White City", "East Acton", 2, true},
    {"Central", "East Acton", "North Acton", 2, true},
    {"Central", "North Acton", "West Acton", 3, true},
    {"Central", "West Acton", "Ealing Broadway", 4, true},
    {"Central", "North Acton", "Hanger Lane", 4, true},
    {"Central", "Hanger Lane", "Perivale", 2, true},
    {"Central", "Perivale", "Greenford", 2, true},
    {"Central", "Greenford", "Northolt", 3, true},
    {"Central", "Northolt", "South Ruislip", 2, true},
    {"Central", "South Ruislip", "Ruislip Gardens", 2, true},
    {"Central", "Ruislip Gardens", "West Ruislip", 3, true},

    /* Adjacent stations on the Circle Line */
    {"Circle", "Hammersmith", "Goldhawk Road", 2, true},
    {"Circle", "Goldhawk Road", "Shepherd's Bush Market", 2, true},
    {"Circle", "Shepherd's Bush Market", "Wood Lane", 1, true},
    {"Circle", "Wood Lane", "Latimer Road", 2, true},
    {"Circle", "Latimer Road", "Ladbroke Grove", 1, true},
    {"Circle", "Ladbroke Grove", "Westbourne Park", 2, true},
    {"Circle", "Westbourne Park", "Royal Oak", 2, true},
    {"Circle", "Royal Oak", "Paddington", 2, true},
    {"Circle", "Paddington", "Edgware Road (Circle/District/H&C)", 3, true},
    {"Circle", "Edgware Road (Circle/District/H&C)", "Baker Street", 3, true},
    {"Circle", "Baker Street", "Great Portland Street", 2, true},
    {"Circle", "Great Portland Street", "Euston Square", 2, true},
    {"Circle", "Euston Square", "King's Cross St Pancras", 2, true},
    {"Circle", "King's Cross St Pancras", "Farringdon", 3, true},
    {"Circle", "Farringdon", "Barbican", 2, true},
    {"Circle", "Barbican", "Moorgate", 2, true},
    {"Circle", "Moorgate", "Liverpool Street", 2, true},
    {"Circle", "Liverpool Street", "Aldgate", 3, true},
    {"Circle", "Aldgate", "Tower Hill", 3, true},
    {"Circle", "Tower Hill", "Monument", 2, true},
    {"Circle", "Monument", "Cannon Street", 1, true},
    {"Circle", "Cannon Street", "Mansion House", 2, true},
    {"Circle", "Mansion House", "Blackfriars", 1, true},
    {"Circle", "Blackfriars", "Temple", 2, true},
    {"Circle", "Temple", "Embankment", 2, true},
    {"Circle", "Embankment", "Westminster", 1, true},
    {"Circle", "Westminster", "St James's Park", 2, true},
    {"Circle", "St James's Park", "Victoria", 2, true},
    {"Circle", "Victoria", "Sloane Square", 2, true},
    {"Circle", "Sloane Square", "South Kensington", 3, true},
    {"Circle", "South Kensington", "Gloucester Road", 2, true},
    {"Circle", "Gloucester Road", "High Street Kensington", 2, true},
    {"Circle", "High Street Kensington", "Notting Hill Gate", 2, true},
    {"Circle", "Notting Hill Gate", "Bayswater", 2, true},
    {"Circle", "Bayswater", "Paddington", 2, true},

    /* Adjacent stations on the District Line */
    {"District", "Upminster", "Upminster Bridge", 2, true},
    {"District", "Upminster Bridge", "Hornchurch", 2, true},
    {"District", "Hornchurch", "Elm Park", 2, true},
    {"District", "Elm Park", "Dagenham East", 3, true},
    {"District", "Dagenham East", "Dagenham Heathway", 2, true},
    {"District", "Dagenham Heathway", "Becontree", 2, true},
    {"District", "Becontree", "Upney", 3, true},
    {"District", "Upney", "Barking", 3, true},
    {"District", "Barking", "East Ham", 3, true},
    {"District", "East Ham", "Upton Park", 2, true},
    {"District", "Upton Park", "Plaistow", 2, true},
    {"District", "Plaistow", "West Ham", 2, true},
    {"District", "West Ham", "Bromley-by-Bow", 2, true},
    {"District", "Bromley-by-Bow", "Bow Road", 3, true},
    {"District", "Bow Road", "Mile End", 1, true},
    {"District", "Mile End", "Stepney Green", 2, true},
    {"District", "Stepney Green", "Whitechapel", 3, true},
    {"District", "Whitechapel", "Aldgate East", 3, true},
    {"District", "Aldgate East", "Tower Hill", 2, true},
    {"District", "Tower Hill", "Monument", 1, true},
    {"District", "Monument", "Cannon Street", 1, true},
    {"District", "Cannon Street", "Mansion House", 2, true},
    {"District", "Mansion House", "Blackfriars", 1, true},
    {"District", "Blackfriars", "Temple", 2, true},
    {"District", "Temple", "Embankment", 2, true},
    {"District", "Embankment", "Westminster", 1, true},
    {"District", "Westminster", "St James's Park", 2, true},
    {"District", "St James's Park", "Victoria", 2, true},
    {"District", "Victoria", "Sloane Square", 2, true},
    {"District", "Sloane Square", "South Kensington", 3, true},
    {"District", "South Kensington", "Gloucester Road", 2, true},
    {"District", "Gloucester Road", "Earl's Court", 2, true},
    {"District", "Earl's Court", "West Brompton", 2, true},
    {"District", "West Brompton", "Fulham Broadway", 2, true},
    {"District", "Fulham Broadway", "Parsons Green", 1, true},
    {"District", "Parsons Green", "Putney Bridge", 2, true},
    {"District", "Putney Bridge", "East Putney", 2, true},
    {"District", "East Putney", "Southfields", 3, true},
    {"District", "Southfields", "Wimbledon Park", 2, true},
    {"District", "Wimbledon Park", "Wimbledon", 4, true},
    {"District", "Earl's Court", "High Street Kensington", 3, true},
    {"District", "High Street Kensington", "Notting Hill Gate", 2, true},
    {"District", "Notting Hill Gate", "Bayswater", 2, true},
    {"District", "Bayswater", "Paddington", 2, true},
    {"District", "Paddington", "Edgware Road (Circle/District/H&C)", 3, true},
    {"District", "Earl's Court", "West Kensington", 2, true},
    {"District", "West Kensington", "Barons Court", 1, true},
    {"District", "Barons Court", "Hammersmith", 2, true},
    {"District", "Hammersmith", "Ravenscourt Park", 2, true},
    {"District", "Ravenscourt Park", "Stamford Brook", 2, true},
    {"District", "Stamford Brook", "Turnham Green", 1, true},
    {"District", "Turnham Green", "Gunnersbury", 3, true},
    {"District", "Gunnersbury", "Kew Gardens", 3, true},
    {"District", "Kew Gardens", "Richmond", 4, true},
    {"District", "Turnham Green", "Chiswick Park", 2, true},
    {"District", "Chiswick Park", "Acton Town", 2, true},
    {"District", "Acton Town", "Ealing Common", 3, true},
    {"District", "Ealing Common", "Ealing Broadway", 4, true},

    /* Adjacent stations on the Hammersmith & City Line */
    {"Hammersmith & City", "Hammersmith", "Goldhawk Road", 2, true},
    {"Hammersmith & City", "Goldhawk Road", "Shepherd's Bush Market", 2, true},
    {"Hammersmith & City", "Shepherd's Bush Market", "Wood Lane", 1, true},
    {"Hammersmith & City", "Wood Lane", "Latimer Road", 2, true},
    {"Hammersmith & City", "Latimer Road", "Ladbroke Grove", 1, true},
    {"Hammersmith & City", "Ladbroke Grove", "Westbourne Park", 2, true},
    {"Hammersmith & City", "Westbourne Park", "Royal Oak", 2, true},
    {"Hammersmith & City", "Royal Oak", "Paddington", 2, true},
    {"Hammersmith & City", "Paddington", "Edgware Road (Circle/District/H&C)", 3, true},
    {"Hammersmith & City", "Edgware Road (Circle/District/H&C)", "Baker Street", 3, true},
    {"Hammersmith & City", "Baker Street", "Great Portland Street", 2, true},
    {"Hammersmith & City", "Great Portland Street", "Euston Square", 2, true},
    {"Hammersmith & City", "Euston Square", "King's Cross St Pancras", 2, true},
    {"Hammersmith & City", "King's Cross St Pancras", "Farringdon", 3, true},
    {"Hammersmith & City", "Farringdon", "Barbican", 2, true},
    {"Hammersmith & City", "Barbican", "Moorgate", 2, true},
    {"Hammersmith & City", "Moorgate", "Liverpool Street", 2, true},
    {"Hammersmith & City", "Liverpool Street", "Aldgate East", 3, true},
    {"Hammersmith & City", "Aldgate East", "Whitechapel", 2, true},
    {"Hammersmith & City", "Whitechapel", "Stepney Green", 2, true},
    {"Hammersmith & City", "Stepney Green", "Mile End", 2, true},
    {"Hammersmith & City", "Mile End", "Bow Road", 2, true},
    {"Hammersmith & City", "Bow Road", "Bromley-by-Bow", 2, true},
    {"Hammersmith & City", "Bromley-by-Bow", "West Ham", 2, true},
    {"Hammersmith & City", "West Ham", "Plaistow", 2, true},
    {"Hammersmith & City", "Plaistow", "Upton Park", 2, true},
    {"Hammersmith & City", "Upton Park", "East Ham", 2, true},
    {"Hammersmith & City", "East Ham", "Barking", 2, true},
    
    /* Adjacent stations on the Jubilee Line */
    {"Jubilee", "Stratford", "West Ham", 2, true},
    {"Jubilee", "West Ham", "Canning Town", 3, true},
    {"Jubilee", "Canning Town", "North Greenwich", 3, true},
    {"Jubilee", "North Greenwich", "Canary Wharf", 2, true},
    {"Jubilee", "Canary Wharf", "Canada Water", 2, true},
    {"Jubilee", "Canada Water", "Bermondsey", 2, true},
    {"Jubilee", "Bermondsey", "London Bridge", 2, true},
    {"Jubilee", "London Bridge", "Southwark", 2, true},
    {"Jubilee", "Southwark", "Waterloo", 1, true},
    {"Jubilee", "Waterloo", "Westminster", 2, true},
    {"Jubilee", "Westminster", "Green Park", 2, true},
    {"Jubilee", "Green Park", "Bond Street", 2, true},
    {"Jubilee", "Bond Street", "Baker Street", 2, true},
    {"Jubilee", "Baker Street", "St John's Wood", 3, true},
    {"Jubilee", "St John's Wood", "Swiss Cottage", 2, true},
    {"Jubilee", "Swiss Cottage", "Finchley Road", 1, true},
    {"Jubilee", "Finchley Road", "West Hampstead", 2, true},
    {"Jubilee", "West Hampstead", "Kilburn", 2, true},
    {"Jubilee", "Kilburn", "Willesden Green", 2, true},
    {"Jubilee", "Willesden Green", "Dollis Hill", 2, true},
    {"Jubilee", "Dollis Hill", "Neasden", 1, true},
    {"Jubilee", "Neasden", "Wembley Park", 4, true},
    {"Jubilee", "Wembley Park", "Kingsbury", 3, true},
    {"Jubilee", "Kingsbury", "Queensbury", 2, true},
    {"Jubilee", "Queensbury", "Canons Park", 2, true},
    {"Jubilee", "Canons Park", "Stanmore", 3, true},
    
    /* Adjacent stations on the Metropolitan Line */
    {"Metropolitan", "Aldgate", "Liverpool Street", 2, true},
    {"Metropolitan", "Liverpool Street", "Moorgate", 1, true},
    {"Metropolitan", "Moorgate", "Barbican", 2, true},
    {"Metropolitan", "Barbican", "Farringdon", 2, true},
    {"Metropolitan", "Farringdon", "King's Cross St Pancras", 3, true},
    {"Metropolitan", "King's Cross St Pancras", "Euston Square", 2, true},
    {"Metropolitan", "Euston Square", "Great Portland Street", 2, true},
    {"Metropolitan", "Great Portland Street", "Baker Street", 2, true},
    {"Metropolitan", "Baker Street", "Finchley Road", 5, true},
    {"Metropolitan", "Finchley Road", "Wembley Park", 7, true},
    {"Metropolitan", "Wembley Park", "Preston Road", 2, true},
    {"Metropolitan", "Preston Road", "Northwick Park", 3, true},
    {"Metropolitan", "Northwick Park", "Harrow-on-the-Hill", 4, true},
    {"Metropolitan", "Harrow-on-the-Hill", "West Harrow", 2, true},
    {"Metropolitan", "West Harrow", "Rayners Lane", 2, true},
    {"Metropolitan", "Rayners Lane", "Eastcote", 2, true},
    {"Metropolitan", "Eastcote", "Ruislip Manor", 1, true},
    {"Metropolitan", "Ruislip Manor", "Ruislip", 3, true},
    {"Metropolitan", "Ruislip", "Ickenham", 2, true},
    {"Metropolitan", "Ickenham", "Hillingdon", 2, true},
    {"Metropolitan", "Hillingdon", "Uxbridge", 4, true},
    {"Metropolitan", "Harrow-on-the-Hill", "North Harrow", 3, true},
    {"Metropolitan", "North Harrow", "Pinner", 2, true},
    {"Metropolitan", "Pinner", "Northwood Hills", 2, true},
    {"Metropolitan", "Northwood Hills", "Northwood", 3, true},
    {"Metropolitan", "Northwood", "Moor Park", 2, true},
    {"Metropolitan", "Moor Park", "Croxley", 4, true},
    {"Metropolitan", "Croxley", "Watford", 4, true},
    {"Metropolitan", "Moor Park", "Rickmansworth", 5, true},
    {"Metropolitan", "Rickmansworth", "Chorleywood", 4, true},
    {"Metropolitan", "Chorleywood", "Chalfont & Latimer", 4, true},
    {"Metropolitan", "Chalfont & Latimer", "Amersham", 5, true},
    {"Metropolitan", "Chalfont & Latimer", "Chesham", 9, true},
    
    /* Adjacent stations on the Northern Line */
    {"Northern", "Morden", "South Wimbledon", 2, true},
    {"Northern", "South Wimbledon", "Colliers Wood", 2, true},
    {"Northern", "Colliers Wood", "Tooting Broadway", 2, true},
    {"Northern", "Tooting Broadway", "Tooting Bec", 2, true},
    {"Northern", "Tooting Bec", "Balham", 2, true},
    {"Northern", "Balham", "Clapham South", 2, true},
    {"Northern", "Clapham South", "Clapham Common", 2, true},
    {"Northern", "Clapham Common", "Clapham North", 1, true},
    {"Northern", "Clapham North", "Stockwell", 2, true},
    {"Northern", "Stockwell", "Oval", 2, true},
    {"Northern", "Oval", "Kennington", 3, true},
    {"Northern", "Kennington", "Waterloo", 2, true},
    {"Northern", "Waterloo", "Embankment", 2, true},
    {"Northern", "Embankment", "Charing Cross", 1, true},
    {"Northern", "Charing Cross", "Leicester Square", 1, true},
    {"Northern", "Leicester Square", "Tottenham Court Road", 2, true},
    {"Northern", "Tottenham Court Road", "Goodge Street", 1, true},
    {"Northern", "Goodge Street", "Warren Street", 1, true},
    {"Northern", "Warren Street", "Euston", 2, true},
    {"Northern", "Kennington", "Elephant & Castle", 2, true},
    {"Northern", "Elephant & Castle", "Borough", 2, true},
    {"Northern", "Borough", "London Bridge", 2, true},
    {"Northern", "London Bridge", "Bank", 1, true},
    {"Northern", "Bank", "Moorgate", 2, true},
    {"Northern", "Moorgate", "Old Street", 2, true},
    {"Northern", "Old Street", "Angel", 3, true},
    {"Northern", "Angel", "King's Cross St Pancras", 2, true},
    {"Northern", "King's Cross St Pancras", "Euston", 2, true},
    {"Northern", "Euston", "Mornington Crescent", 2, true},
    {"Northern", "Mornington Crescent", "Camden Town", 2, true},
    {"Northern", "Camden Town", "Chalk Farm", 2, true},
    {"Northern", "Chalk Farm", "Belsize Park", 2, true},
    {"Northern", "Belsize Park", "Hampstead", 2, true},
    {"Northern", "Hampstead", "Golders Green", 4, true},
    {"Northern", "Golders Green", "Brent Cross", 3, true},
    {"Northern", "Brent Cross", "Hendon Central", 1, true},
    {"Northern", "Hendon Central", "Colindale", 3, true},
    {"Northern", "Colindale", "Burnt Oak", 2, true},
    {"Northern", "Burnt Oak", "Edgware", 3, true},
    {"Northern", "Camden Town", "Kentish Town", 2, true},
    {"Northern", "Kentish Town", "Tufnell Park", 1, true},
    {"Northern", "Tufnell Park", "Archway", 2, true},
    {"Northern", "Archway", "Highgate", 3, true},
    {"Northern", "Highgate", "East Finchley", 2, true},
    {"Northern", "East Finchley", "Finchley Central", 4, true},
    {"Northern", "Finchley Central", "Mill Hill East", 3, true},
    {"Northern", "Finchley Central", "West Finchley", 2, true},
    {"Northern", "West Finchley", "Woodside Park", 2, true},
    {"Northern", "Woodside Park", "Totteridge & Whetstone", 2, true},
    {"Northern", "Totteridge & Whetstone", "High Barnet", 4, true},

    /* Adjacent stations on the Piccadilly Line */
    {"Piccadilly", "Cockfosters", "Oakwood", 2, true},
    {"Piccadilly", "Oakwood", "Southgate", 3, true},
    {"Piccadilly", "Southgate", "Arnos Grove", 5, true},
    {"Piccadilly", "Arnos Grove", "Bounds Green", 2, true},
    {"Piccadilly", "Bounds Green", "Wood Green", 2, true},
    {"Piccadilly", "Wood Green", "Turnpike Lane", 2, true},
    {"Piccadilly", "Turnpike Lane", "Manor House", 3, true},
    {"Piccadilly", "Manor House", "Finsbury Park", 3, true},
    {"Piccadilly", "Finsbury Park", "Arsenal", 1, true},
    {"Piccadilly", "Arsenal", "Holloway Road", 2, true},
    {"Piccadilly", "Holloway Road", "Caledonian Road", 1, true},
    {"Piccadilly", "Caledonian Road", "King's Cross St Pancras", 4, true},
    {"Piccadilly", "King's Cross St Pancras", "Russell Square", 2, true},
    {"Piccadilly", "Russell Square", "Holborn", 1, true},
    {"Piccadilly", "Holborn", "Covent Garden", 2, true},
    {"Piccadilly", "Covent Garden", "Leicester Square", 1, true},
    {"Piccadilly", "Leicester Square", "Piccadilly Circus", 2, true},
    {"Piccadilly", "Piccadilly Circus", "Green Park", 2, true},
    {"Piccadilly", "Green Park", "Hyde Park Corner", 2, true},
    {"Piccadilly", "Hyde Park Corner", "Knightsbridge", 1, true},
    {"Piccadilly", "Knightsbridge", "South Kensington", 3, true},
    {"Piccadilly", "South Kensington", "Gloucester Road", 1, true},
    {"Piccadilly", "Gloucester Road", "Earl's Court", 3, true},
    {"Piccadilly", "Earl's Court", "Barons Court", 3, true},
    {"Piccadilly", "Barons Court", "Hammersmith", 2, true},
    {"Piccadilly", "Hammersmith", "Turnham Green", 4, true},
    {"Piccadilly", "Turnham Green", "Acton Town", 4, true},
    {"Piccadilly", "Acton Town", "South Ealing", 3, true},
    {"Piccadilly", "South Ealing", "Northfields", 3, true},
    {"Piccadilly", "Northfields", "Boston Manor", 2, true},
    {"Piccadilly", "Boston Manor", "Osterley", 3, true},
    {"Piccadilly", "Osterley", "Hounslow East", 2, true},
    {"Piccadilly", "Hounslow East", "Hounslow Central", 1, true},
    {"Piccadilly", "Hounslow Central", "Hounslow West", 3, true},
    {"Piccadilly", "Hounslow West", "Hatton Cross", 5, true},
    {"Piccadilly", "Hatton Cross", "Heathrow Terminal 4", 3, false},
    {"Piccadilly", "Heathrow Terminal 4", "Heathrow Terminals 2 & 3", 5, false},
    {"Piccadilly", "Hatton Cross", "Heathrow Terminals 2 & 3", 4, true},
    {"Piccadilly", "Heathrow Terminals 2 & 3", "Heathrow Terminal 5", 3, true},
    {"Piccadilly", "Acton Town", "Ealing Common", 2, true},
    {"Piccadilly", "Ealing Common", "North Ealing", 2, true},
    {"Piccadilly", "North Ealing", "Park Royal", 2, true},
    {"Piccadilly", "Park Royal", "Alperton", 3, true},
    {"Piccadilly", "Alperton", "Sudbury Town", 2, true},
    {"Piccadilly", "Sudbury Town", "Sudbury Hill", 3, true},
    {"Piccadilly", "Sudbury Hill", "South Harrow", 2, true},
    {"Piccadilly", "South Harrow", "Rayners Lane", 4, true},
    {"Piccadilly", "Rayners Lane", "Eastcote", 2, true},
    {"Piccadilly", "Eastcote", "Ruislip Manor", 1, true},
    {"Piccadilly", "Ruislip Manor", "Ruislip", 3, true},
    {"Piccadilly", "Ruislip", "Ickenham", 2, true},
    {"Piccadilly", "Ickenham", "Hillingdon", 2, true},
    {"Piccadilly", "Hillingdon", "Uxbridge", 4, true},
    
    /* Adjacent stations on the Victoria Line */
    {"Victoria", "Brixton", "Stockwell", 2, true},
    {"Victoria", "Stockwell", "Vauxhall", 2, true},
    {"Victoria", "Vauxhall", "Pimlico", 2, true},
    {"Victoria", "Pimlico", "Victoria", 2, true},
    {"Victoria", "Victoria", "Green Park", 2, true},
    {"Victoria", "Green Park", "Oxford Circus", 2, true},
    {"Victoria", "Oxford Circus", "Warren Street", 1, true},
    {"Victoria", "Warren Street", "Euston", 2, true},
    {"Victoria", "Euston", "King's Cross St Pancras", 1, true},
    {"Victoria", "King's Cross St Pancras", "Highbury & Islington", 3, true},
    {"Victoria", "Highbury & Islington", "Finsbury Park", 2, true},
    {"Victoria", "Finsbury Park", "Seven Sisters", 4, true},
    {"Victoria", "Seven Sisters", "Tottenham Hale", 2, true},
    {"Victoria", "Tottenham Hale", "Blackhorse Road", 2, true},
    {"Victoria", "Blackhorse Road", "Walthamstow Central", 2, true},
    
    /* Adjacent stations on the Waterloo & City Line */
    {"Waterloo & City", "Waterloo", "Bank", 4, true},

    /* Adjacent stations on the Docklands Light Railway (DLR) Line */
    {"DLR", "Lewisham", "Elverson Road", 1, true},
    {"DLR", "Elverson Road", "Deptford Bridge", 2, true},
    {"DLR", "Deptford Bridge", "Greenwich", 2, true},
    {"DLR", "Greenwich", "Cutty Sark for Maritime Greenwich", 2, true},
    {"DLR", "Cutty Sark for Maritime Greenwich", "Island Gardens", 2, true},
    {"DLR", "Island Gardens", "Mudchute", 1, true},
    {"DLR", "Mudchute", "Crossharbour", 1, true},
    {"DLR", "Crossharbour", "South Quay", 2, true},
    {"DLR", "South Quay", "Heron Quays", 2, true},
    {"DLR", "Heron Quays", "Canary Wharf", 1, true},
    {"DLR", "Canary Wharf", "West India Quay", 2, true},
    {"DLR", "West India Quay", "Westferry", 2, true},
    {"DLR", "Westferry", "Limehouse", 2, true},
    {"DLR", "Limehouse", "Shadwell", 4, true},
    {"DLR", "Shadwell", "Tower Gateway", 3, true},
    {"DLR", "Shadwell", "Bank", 3, true},
    {"DLR", "Westferry", "Poplar", 1, true},
    {"DLR", "West India Quay", "Poplar", 1, true},
    {"DLR", "Poplar", "All Saints", 3, true},
    {"DLR", "All Saints", "Langdon Park", 1, true},
    {"DLR", "Langdon Park", "Devons Road", 2, true},
    {"DLR", "Devons Road", "Bow Church", 1, true},
    {"DLR", "Bow Church", "Pudding Mill Lane", 2, true},
    {"DLR", "Pudding Mill Lane", "Stratford", 9, true},
    {"DLR", "Stratford", "Stratford International", 5, true},
    {"DLR", "Poplar", "Blackwall", 2, true},
    {"DLR", "Blackwall", "East India", 1, true},
    {"DLR", "East India", "Canning Town", 2, true},
    {"DLR", "Canning Town", "Star Lane", 2, true},
    {"DLR", "Star Lane", "West Ham", 2, true},
    {"DLR", "West Ham", "Abbey Road", 1, true},
    {"DLR", "Abbey Road", "Stratford High Street", 1, true},
    {"DLR", "Stratford High Street", "Stratford", 1, true},
    {"DLR", "Canning Town", "Royal Victoria", 2, true},
    {"DLR", "Royal Victoria", "Custom House for ExCeL", 1, true},
    {"DLR", "Custom House for ExCeL", "Prince Regent", 1, true},
    {"DLR", "Prince Regent", "Royal Albert", 2, true},
    {"DLR", "Royal Albert", "Beckton Park", 1, true},
    {"DLR", "Beckton Park", "Cyprus", 1, true},
    {"DLR", "Cyprus", "Gallions Reach", 2, true},
    {"DLR", "Gallions Reach", "Beckton", 2, true},
    {"DLR", "Canning Town", "West Silvertown", 5, true},
    {"DLR", "West Silvertown", "Pontoon Dock", 4, true},
    {"DLR", "Pontoon Dock", "London City Airport", 2, true},
    {"DLR", "London City Airport", "King George V", 2, true},
    {"DLR", "King George V", "Woolwich Arsenal", 3, true},

    /* Adjacent stations on the London Overground Line */
    {"London Overground", "Richmond", "Kew Gardens", 3, true},
    {"London Overground", "Kew Gardens", "Gunnersbury", 3, true},
    {"London Overground", "Gunnersbury", "South Acton", 3, true},
    {"London Overground", "South Acton", "Acton Central", 3, true},
    {"London Overground", "Acton Central", "Willesden Junction", 7, true},
    {"London Overground", "Willesden Junction", "Shepherd's Bush", 9, true},
    {"London Overground", "Shepherd's Bush", "Kensington (Olympia)", 2, true},
    {"London Overground", "Kensington (Olympia)", "West Brompton", 3, true},
    {"London Overground", "West Brompton", "Imperial Wharf", 3, true},
    {"London Overground", "Imperial Wharf", "Clapham Junction", 4, true},
    {"London Overground", "Willesden Junction", "Kensal Rise", 3, true},
    {"London Overground", "Kensal Rise", "Brondesbury Park", 2, true},
    {"London Overground", "Brondesbury Park", "Brondesbury", 2, true},
    {"London Overground", "Brondesbury", "West Hampstead", 2, true},
    {"London Overground", "West Hampstead", "Finchley Road & Frognal", 1, true},
    {"London Overground", "Finchley Road & Frognal", "Hampstead Heath", 3, true},
    {"London Overground", "Hampstead Heath", "Gospel Oak", 3, true},
    {"London Overground", "Gospel Oak", "Kentish Town West", 2, true},
    {"London Overground", "Kentish Town West", "Camden Road", 3, true},
    {"London Overground", "Camden Road", "Caledonian Road & Barnsbury", 3, true},
    {"London Overground", "Caledonian Road & Barnsbury", "Highbury & Islington", 3, true},
    {"London Overground", "Highbury & Islington", "Canonbury", 2, true},
    {"London Overground", "Canonbury", "Dalston Kingsland", 2, true},
    {"London Overground", "Dalston Kingsland", "Hackney Central", 2, true},
    {"London Overground", "Hackney Central", "Homerton", 2, true},
    {"London Overground", "Hackney Central", "Hackney Downs", 6, true},
    {"London Overground", "Homerton", "Hackney Wick", 2, true},
    {"London Overground", "Hackney Wick", "Stratford", 7, true},
    {"London Overground", "Watford Junction", "Watford High Street", 3, true},
    {"London Overground", "Watford High Street", "Bushey", 2, true},
    {"London Overground", "Bushey", "Carpenders Park", 3, true},
    {"London Overground", "Carpenders Park", "Hatch End", 3, true},
    {"London Overground", "Hatch End", "Headstone Lane", 2, true},
    {"London Overground", "Headstone Lane", "Harrow & Wealdstone", 3, true},
    {"London Overground", "Harrow & Wealdstone", "Kenton", 3, true},
    {"London Overground", "Kenton", "South Kenton", 2, true},
    {"London Overground", "South Kenton", "North Wembley", 2, true},
    {"London Overground", "North Wembley", "Wembley Central", 2, true},
    {"London Overground", "Wembley Central", "Stonebridge Park", 3, true},
    {"London Overground", "Stonebridge Park", "Harlesden", 2, true},
    {"London Overground", "Harlesden", "Willesden Junction", 3, true},
    {"London Overground", "Willesden Junction", "Kensal Green", 2, true},
    {"London Overground", "Kensal Green", "Queen's Park", 3, true},
    {"London Overground", "Queen's Park", "Kilburn High Road", 2, true},
    {"London Overground", "Kilburn High Road", "South Hampstead", 2, true},
    {"London Overground", "South Hampstead", "Euston", 10, true},
    {"London Overground", "Romford", "Emerson Park", 4, true},
    {"London Overground", "Emerson Park", "Upminster", 5, true},
    {"London Overground", "Gospel Oak", "Upper Holloway", 4, true},
    {"London Overground", "Upper Holloway", "Crouch Hill", 2, true},
    {"London Overground", "Crouch Hill", "Harringay Green Lanes", 3, true},
    {"London Overground", "Harringay Green Lanes", "South Tottenham", 4, true},
    {"London Overground", "South Tottenham", "Blackhorse Road", 4, true},
    {"London Overground", "Blackhorse Road", "Walthamstow Queen's Road", 2, true},
    {"London Overground", "Walthamstow Queen's Road", "Leyton Midland Road", 3, true},
    {"London Overground", "Leyton Midland Road", "Leytonstone High Road", 2, true},
    {"London Overground", "Leytonstone High Road", "Wanstead Park", 2, true},
    {"London Overground", "Wanstead Park", "Woodgrange Park", 3, true},
    {"London Overground", "Woodgrange Park", "Barking", 5, true},
    {"London Overground", "Liverpool Street", "Bethnal Green (London Overground)", 3, true},
    {"London Overground", "Bethnal Green (London Overground)", "Cambridge Heath", 2, true},
    {"London Overground", "Cambridge Heath", "London Fields", 2, true},
    {"London Overground", "London Fields", "Hackney Downs", 2, true},
    {"London Overground", "Hackney Downs", "Clapton", 3, true},
    {"London Overground", "Clapton", "St James Street", 4, true},
    {"London Overground", "St James Street", "Walthamstow Central", 2, true},
    {"London Overground", "Walthamstow Central", "Wood Street", 2, true},
    {"London Overground", "Walthamstow Central", "Walthamstow Queen's Road", 7, true},
    {"London Overground", "Wood Street", "Highams Park", 3, true},
    {"London Overground", "Highams Park", "Chingford", 6, true},
    {"London Overground", "Hackney Downs", "Rectory Road", 3, true},
    {"London Overground", "Rectory Road", "Stoke Newington", 1, true},
    {"London Overground", "Stoke Newington", "Stamford Hill", 2, true},
    {"London Overground", "Stamford Hill", "Seven Sisters", 3, true},
    {"London Overground", "Seven Sisters", "Bruce Grove", 2, true},
    {"London Overground", "Bruce Grove", "White Hart Lane", 2, true},
    {"London Overground", "White Hart Lane", "Silver Street", 2, true},
    {"London Overground", "Silver Street", "Edmonton Green", 2, true},
    {"London Overground", "Edmonton Green", "Bush Hill Park", 3, true},
    {"London Overground", "Bush Hill Park", "Enfield Town", 5, true},
    {"London Overground", "Edmonton Green", "Southbury", 3, true},
    {"London Overground", "Southbury", "Turkey Street", 3, true},
    {"London Overground", "Turkey Street", "Theobalds Grove", 3, true},
    {"London Overground", "Theobalds Grove", "Cheshunt", 5, true},
    {"London Overground", "Highbury & Islington", "Canonbury", 2, true},
    {"London Overground", "Canonbury", "Dalston Junction", 3, true},
    {"London Overground", "Dalston Junction", "Haggerston", 2, true},
    {"London Overground", "Haggerston", "Hoxton", 2, true},
    {"London Overground", "Hoxton", "Shoreditch High Street", 2, true},
    {"London Overground", "Shoreditch High Street", "Whitechapel", 3, true},
    {"London Overground", "Whitechapel", "Shadwell", 2, true},
    {"London Overground", "Shadwell", "Wapping", 2, true},
    {"London Overground", "Wapping", "Rotherhithe", 1, true},
    {"London Overground", "Rotherhithe", "Canada Water", 2, true},
    {"London Overground", "Canada Water", "Surrey Quays", 2, true},
    {"London Overground", "Surrey Quays", "New Cross", 4, true},
    {"London Overground", "Surrey Quays", "Queens Road Peckham", 6, true},
    {"London Overground", "Queens Road Peckham", "Peckham Rye", 2, true},
    {"London Overground", "Peckham Rye", "Denmark Hill", 4, true},
    {"London Overground", "Denmark Hill", "Clapham High Street", 4, true},
    {"London Overground", "Clapham High Street", "Wandsworth Road", 2, true},
    {"London Overground", "Wandsworth Road", "Clapham Junction", 7, true},
    {"London Overground", "Surrey Quays", "New Cross Gate", 4, true},
    {"London Overground", "New Cross Gate", "Brockley", 3, true},
    {"London Overground", "Brockley", "Honor Oak Park", 2, true},
    {"London Overground", "Honor Oak Park", "Forest Hill", 3, true},
    {"London Overground", "Forest Hill", "Sydenham", 3, true},
    {"London Overground", "Sydenham", "Crystal Palace", 5, true},
    {"London Overground", "Sydenham", "Penge West", 2, true},
    {"London Overground", "Penge West", "Anerley", 2, true},
    {"London Overground", "Anerley", "Norwood Junction", 3, true},
    {"London Overground", "Norwood Junction", "West Croydon", 6, true},

    /* Adjacent stations on the TfL Rail Line */
    {"TfL Rail", "Liverpool Street", "Stratford", 7, true},
    {"TfL Rail", "Stratford", "Maryland", 2, true},
    {"TfL Rail", "Maryland", "Forest Gate", 2, true},
    {"TfL Rail", "Forest Gate", "Manor Park", 2, true},
    {"TfL Rail", "Manor Park", "Ilford", 3, true},
    {"TfL Rail", "Ilford", "Seven Kings", 2, true},
    {"TfL Rail", "Seven Kings", "Goodmayes", 2, true},
    {"TfL Rail", "Goodmayes", "Chadwell Heath", 2, true},
    {"TfL Rail", "Chadwell Heath", "Romford", 4, true},
    {"TfL Rail", "Romford", "Gidea Park", 2, true},
    {"TfL Rail", "Gidea Park", "Harold Wood", 2, true},
    {"TfL Rail", "Harold Wood", "Brentwood", 4, true},
    {"TfL Rail", "Brentwood", "Shenfield", 6, true},
    {"TfL Rail", "Paddington", "Acton Main Line", 6, true},
    {"TfL Rail", "Acton Main Line", "Ealing Broadway", 3, true},
    {"TfL Rail", "Ealing Broadway", "West Ealing", 3, true},
    {"TfL Rail", "West Ealing", "Hanwell", 2, true},
    {"TfL Rail", "Hanwell", "Southall", 4, true},
    {"TfL Rail", "Southall", "Hayes & Harlington", 4, true},
    {"TfL Rail", "Hayes & Harlington", "Heathrow Terminals 2 & 3", 9, true},
    {"TfL Rail", "Heathrow Terminals 2 & 3", "Heathrow Terminal 4", 4, true},

    /* Adjacent stations on the Tramlink Line */
    {"Tramlink", "Wimbledon", "Dundonald Road", 1, true},
    {"Tramlink", "Dundonald Road", "Merton Park", 2, true},
    {"Tramlink", "Merton Park", "Morden Road", 1, true},
    {"Tramlink", "Morden Road", "Phipps Bridge", 2, true},
    {"Tramlink", "Phipps Bridge", "Belgrave Walk", 1, true},
    {"Tramlink", "Belgrave Walk", "Mitcham", 2, true},
    {"Tramlink", "Mitcham", "Mitcham Junction", 3, true},
    {"Tramlink", "Mitcham Junction", "Beddington Lane", 2, true},
    {"Tramlink", "Beddington Lane", "Therapia Lane", 2, true},
    {"Tramlink", "Therapia Lane", "Ampere Way", 1, true},
    {"Tramlink", "Ampere Way", "Waddon Marsh", 2, true},
    {"Tramlink", "Waddon Marsh", "Wandle Park", 1, true},
    {"Tramlink", "Wandle Park", "Reeves Corner", 2, false},
    {"Tramlink", "Reeves Corner", "Centrale", 2, false},
    {"Tramlink", "Centrale", "West Croydon", 2, false},
    {"Tramlink", "West Croydon", "Wellesley Road", 3, false},
    {"Tramlink", "Wellesley Road", "East Croydon", 2, false},
    {"Tramlink", "East Croydon", "George Street", 2, false},
    {"Tramlink", "George Street", "Church Street", 2, false},
    {"Tramlink", "Church Street", "Centrale", 2, false},
    {"Tramlink", "Church Street", "Wandle Park", 3, false},
    {"Tramlink", "East Croydon", "Lebanon Road", 2, true},
    {"Tramlink", "Lebanon Road", "Sandilands", 2, true},
    {"Tramlink", "Sandilands", "Lloyd Park", 4, true},
    {"Tramlink", "Lloyd Park", "Coombe Lane", 3, true},
    {"Tramlink", "Coombe Lane", "Gravel Hill", 3, true},
    {"Tramlink", "Gravel Hill", "Addington Village", 2, true},
    {"Tramlink", "Addington Village", "Fieldway", 2, true},
    {"Tramlink", "Fieldway", "King Henry's Drive", 2, true},
    {"Tramlink", "King Henry's Drive", "New Addington", 1, true},
    {"Tramlink", "Sandilands", "Addiscombe", 3, true},
    {"Tramlink", "Addiscombe", "Blackhorse Lane", 2, true},
    {"Tramlink", "Blackhorse Lane", "Woodside", 1, true},
    {"Tramlink", "Woodside", "Arena", 2, true},
    {"Tramlink", "Arena", "Elmers End", 3, true},
    {"Tramlink", "Arena", "Harrington Road", 2, true},
    {"Tramlink", "Harrington Road", "Birkbeck", 3, true},
    {"Tramlink", "Birkbeck", "Avenue Road", 1, true},
    {"Tramlink", "Avenue Road", "Beckenham Road", 1, true},
    {"Tramlink", "Beckenham Road", "Beckenham Junction", 3, true}
};

const std::vector<Interchange> interchanges = {
    /* Transfers to stations on the Bakerloo Line */
    {"Harrow & Wealdstone", "London Overground", "Harrow & Wealdstone", "Bakerloo", 10},
    {"Wembley Central", "London Overground", "Wembley Central", "Bakerloo", 10},
    {"Willesden Junction", "London Overground", "Willesden Junction", "Bakerloo", 7},
    {"Queen's Park", "London Overground", "Queen's Park", "Bakerloo", 3},
    {"Paddington", "Circle", "Paddington", "Bakerloo", 3},
    {"Paddington", "District", "Paddington", "Bakerloo", 3},
    {"Paddington", "Hammersmith & City", "Paddington", "Bakerloo", 3},
    {"Paddington", "TfL Rail", "Paddington", "Bakerloo", 3},
    {"Baker Street", "Circle", "Baker Street", "Bakerloo", 3},
    {"Baker Street", "Hammersmith & City", "Baker Street", "Bakerloo", 3},
    {"Baker Street", "Jubilee", "Baker Street", "Bakerloo", 3},
    {"Baker Street", "Metropolitan", "Baker Street", "Bakerloo", 3},
    {"Oxford Circus", "Central", "Oxford Circus", "Bakerloo", 3},
    {"Oxford Circus", "Victoria", "Oxford Circus", "Bakerloo", 3},
    {"Piccadilly Circus", "Piccadilly", "Piccadilly Circus", "Bakerloo", 3},
    {"Charing Cross", "Northern", "Charing Cross", "Bakerloo", 3},
    {"Embankment", "Circle", "Embankment", "Bakerloo", 3},
    {"Embankment", "District", "Embankment", "Bakerloo", 3},
    {"Embankment", "Northern", "Embankment", "Bakerloo", 3},
    {"Waterloo", "Jubilee", "Waterloo", "Bakerloo", 3},
    {"Waterloo", "Northern", "Waterloo", "Bakerloo", 3},
    {"Waterloo", "Waterloo & City", "Waterloo", "Bakerloo", 3},
    {"Elephant & Castle", "Northern", "Elephant & Castle", "Bakerloo", 3},

    /* Transfers to stations on the Central Line */
    {"Ealing Broadway", "District", "Ealing Broadway", "Central", 7},
    {"Ealing Broadway", "TfL Rail", "Ealing Broadway", "Central", 7},
    {"Wood Lane", "Circle", "White City", "Central", 3},
    {"Wood Lane", "Hammersmith & City", "White City", "Central", 3},
    {"Shepherd's Bush", "London Overground", "Shepherd's Bush", "Central", 3},
    {"Notting Hill Gate", "Circle", "Notting Hill Gate", "Central", 3},
    {"Notting Hill Gate", "District", "Notting Hill Gate", "Central", 3},
    {"Bond Street", "Jubilee", "Bond Street", "Central", 3},
    {"Oxford Circus", "Bakerloo", "Oxford Circus", "Central", 3},
    {"Oxford Circus", "Victoria", "Oxford Circus", "Central", 3},
    {"Tottenham Court Road", "Northern", "Tottenham Court Road", "Central", 3},
    {"Holborn", "Piccadilly", "Holborn", "Central", 3},
    {"Monument", "Circle", "Bank", "Central", 3},
    {"Monument", "District", "Bank", "Central", 3},
    {"Bank", "DLR", "Bank", "Central", 3},
    {"Bank", "Northern", "Bank", "Central", 3},
    {"Bank", "Waterloo & City", "Bank", "Central", 3},
    {"Liverpool Street", "Circle", "Liverpool Street", "Central", 3},
    {"Liverpool Street", "Hammersmith & City", "Liverpool Street", "Central", 3},
    {"Liverpool Street", "London Overground", "Liverpool Street", "Central", 3},
    {"Liverpool Street", "Metropolitan", "Liverpool Street", "Central", 3},
    {"Liverpool Street", "TfL Rail", "Liverpool Street", "Central", 3},
    {"Mile End", "District", "Mile End", "Central", 3},
    {"Mile End", "Hammersmith & City", "Mile End", "Central", 3},
    {"Stratford", "DLR", "Stratford", "Central", 3},
    {"Stratford", "Jubilee", "Stratford", "Central", 3},
    {"Stratford", "London Overground", "Stratford", "Central", 3},
    {"Stratford", "TfL Rail", "Stratford", "Central", 3},

    /* Transfers to stations on the Circle Line */
    {"Hammersmith", "District", "Hammersmith", "Circle", 10},
    {"Hammersmith", "Hammersmith & City", "Hammersmith", "Circle", 10},
    {"Hammersmith", "Piccadilly", "Hammersmith", "Circle", 10},
    {"White City", "Central", "Wood Lane", "Circle", 10},
    {"Wood Lane", "Hammersmith & City", "Wood Lane", "Circle", 10},
    {"Paddington", "Bakerloo", "Paddington", "Circle", 10},
    {"Paddington", "District", "Paddington", "Circle", 10},
    {"Paddington", "Hammersmith & City", "Paddington", "Circle", 10},
    {"Paddington", "TfL Rail", "Paddington", "Circle", 10},
    {"Edgware Road (Circle/District/H&C)", "District", "Edgware Road (Circle/District/H&C)", "Circle", 10},
    {"Edgware Road (Circle/District/H&C)", "Hammersmith & City", "Edgware Road (Circle/District/H&C)", "Circle", 10},
    {"Baker Street", "Bakerloo", "Baker Street", "Circle", 10},
    {"Baker Street", "Hammersmith & City", "Baker Street", "Circle", 10},
    {"Baker Street", "Jubilee", "Baker Street", "Circle", 10},
    {"Baker Street", "Metropolitan", "Baker Street", "Circle", 10},
    {"King's Cross St Pancras", "Hammersmith & City", "King's Cross St Pancras", "Circle", 10},
    {"King's Cross St Pancras", "Metropolitan", "King's Cross St Pancras", "Circle", 10},
    {"King's Cross St Pancras", "Northern", "King's Cross St Pancras", "Circle", 10},
    {"King's Cross St Pancras", "Piccadilly", "King's Cross St Pancras", "Circle", 10},
    {"King's Cross St Pancras", "Victoria", "King's Cross St Pancras", "Circle", 10},
    {"Farringdon", "Hammersmith & City", "Farringdon", "Circle", 10},
    {"Farringdon", "Metropolitan", "Farringdon", "Circle", 10},
    {"Moorgate", "Hammersmith & City", "Moorgate", "Circle", 10},
    {"Moorgate", "Metropolitan", "Moorgate", "Circle", 10},
    {"Moorgate", "Northern", "Moorgate", "Circle", 10},
    {"Liverpool Street", "Central", "Liverpool Street", "Circle", 10},
    {"Liverpool Street", "Hammersmith & City", "Liverpool Street", "Circle", 10},
    {"Liverpool Street", "London Overground", "Liverpool Street", "Circle", 10},
    {"Liverpool Street", "Metropolitan", "Liverpool Street", "Circle", 10},
    {"Liverpool Street", "TfL Rail", "Liverpool Street", "Circle", 10},
    {"Tower Hill", "District", "Tower Hill", "Circle", 10},
    {"Tower Gateway", "DLR", "Tower Hill", "Circle", 10},
    {"Monument", "District", "Monument", "Circle", 10},
    {"Bank", "Central", "Monument", "Circle", 10},
    {"Bank", "DLR", "Monument", "Circle", 10},
    {"Bank", "Northern", "Monument", "Circle", 10},
    {"Bank", "Waterloo & City", "Monument", "Circle", 10},
    {"Cannon Street", "District", "Cannon Street", "Circle", 10},
    {"Blackfriars", "District", "Blackfriars", "Circle", 10},
    {"Embankment", "Bakerloo", "Embankment", "Circle", 10},
    {"Embankment", "District", "Embankment", "Circle", 10},
    {"Embankment", "Northern", "Embankment", "Circle", 10},
    {"Westminster", "District", "Westminster", "Circle", 10},
    {"Westminster", "Jubilee", "Westminster", "Circle", 10},
    {"Victoria", "District", "Victoria", "Circle", 10},
    {"Victoria", "Victoria", "Victoria", "Circle", 10},
    {"South Kensington", "District", "South Kensington", "Circle", 10},
    {"South Kensington", "Piccadilly", "South Kensington", "Circle", 10},
    {"Notting Hill Gate", "Central", "Notting Hill Gate", "Circle", 10},
    {"Notting Hill Gate", "District", "Notting Hill Gate", "Circle", 10},

    /* Transfers to stations on the District Line */
    {"Ealing Broadway", "Central", "Ealing Broadway", "District", 10},
    {"Ealing Broadway", "TfL Rail", "Ealing Broadway", "District", 10},
    {"Ealing Common", "Piccadilly", "Ealing Common", "District", 10},
    {"Acton Town", "Piccadilly", "Acton Town", "District", 10},
    {"Richmond", "London Overground", "Richmond", "District", 10},
    {"Kew Gardens", "London Overground", "Kew Gardens", "District", 10},
    {"Gunnersbury", "London Overground", "Gunnersbury", "District", 10},
    {"Hammersmith", "Circle", "Hammersmith", "District", 5},
    {"Hammersmith", "Hammersmith & City", "Hammersmith", "District", 5},
    {"Hammersmith", "Piccadilly", "Hammersmith", "District", 5},
    {"Earl's Court", "Piccadilly", "Earl's Court", "District", 4},
    {"Wimbledon", "Tramlink", "Wimbledon", "District", 5},
    {"West Brompton", "London Overground", "West Brompton", "District", 5},
    {"Notting Hill Gate", "Central", "Notting Hill Gate", "District", 10},
    {"Notting Hill Gate", "Circle", "Notting Hill Gate", "District", 10},
    {"Paddington", "Bakerloo", "Paddington", "District", 10},
    {"Paddington", "Circle", "Paddington", "District", 10},
    {"Paddington", "Hammersmith & City", "Paddington", "District", 10},
    {"Paddington", "TfL Rail", "Paddington", "District", 10},
    {"Edgware Road (Circle/District/H&C)", "Circle", "Edgware Road (Circle/District/H&C)", "District", 10},
    {"Edgware Road (Circle/District/H&C)", "Hammersmith & City", "Edgware Road (Circle/District/H&C)", "District", 10},
    {"South Kensington", "Circle", "South Kensington", "District", 3},
    {"South Kensington", "Piccadilly", "South Kensington", "District", 3},
    {"Victoria", "Circle", "Victoria", "District", 3},
    {"Victoria", "Victoria", "Victoria", "District", 3},
    {"Westminster", "Circle", "Westminster", "District", 3},
    {"Westminster", "Jubilee", "Westminster", "District", 3},
    {"Embankment", "Bakerloo", "Embankment", "District", 3},
    {"Embankment", "Circle", "Embankment", "District", 3},
    {"Embankment", "Northern", "Embankment", "District", 3},
    {"Blackfriars", "Circle", "Blackfriars", "District", 3},
    {"Cannon Street", "Circle", "Cannon Street", "District", 3},
    {"Monument", "Circle", "Monument", "District", 3},
    {"Bank", "Central", "Monument", "District", 3},
    {"Bank", "DLR", "Monument", "District", 3},
    {"Bank", "Northern", "Monument", "District", 3},
    {"Bank", "Waterloo & City", "Monument", "District", 3},
    {"Tower Hill", "Circle", "Tower Hill", "District", 3},
    {"Tower Gateway", "DLR", "Tower Hill", "District", 3},
    {"Aldgate East", "Hammersmith & City", "Aldgate East", "District", 4},
    {"Whitechapel", "Hammersmith & City", "Whitechapel", "District", 4},
    {"Whitechapel", "London Overground", "Whitechapel", "District", 4},
    {"Mile End", "Central", "Mile End", "District", 4},
    {"Mile End", "Hammersmith & City", "Mile End", "District", 4},
    {"Bow Church", "DLR", "Bow Road", "District", 4},
    {"Bow Road", "Hammersmith & City", "Bow Road", "District", 4},
    {"Bromley-by-Bow", "Hammersmith & City", "Bromley-by-Bow", "District", 4},
    {"West Ham", "DLR", "West Ham", "District", 4},
    {"West Ham", "Hammersmith & City", "West Ham", "District", 4},
    {"West Ham", "Jubilee", "West Ham", "District", 4},
    {"Barking", "Hammersmith & City", "Barking", "District", 4},
    {"Barking", "London Overground", "Barking", "District", 4},
    {"Upminster", "London Overground", "Upminster", "District", 5},

    /* Transfers to stations on the Hammersmith & City Line */
    {"Hammersmith", "Circle", "Hammersmith", "Hammersmith & City", 10},
    {"Hammersmith", "District", "Hammersmith", "Hammersmith & City", 10},
    {"Hammersmith", "Piccadilly", "Hammersmith", "Hammersmith & City", 10},
    {"White City", "Central", "Wood Lane", "Hammersmith & City", 10},
    {"Wood Lane", "Circle", "Wood Lane", "Hammersmith & City", 10},
    {"Paddington", "Bakerloo", "Paddington", "Hammersmith & City", 10},
    {"Paddington", "Circle", "Paddington", "Hammersmith & City", 10},
    {"Paddington", "District", "Paddington", "Hammersmith & City", 10},
    {"Paddington", "TfL Rail", "Paddington", "Hammersmith & City", 10},
    {"Edgware Road (Circle/District/H&C)", "Circle", "Edgware Road (Circle/District/H&C)", "Hammersmith & City", 10},
    {"Edgware Road (Circle/District/H&C)", "District", "Edgware Road (Circle/District/H&C)", "Hammersmith & City", 10},
    {"Baker Street", "Bakerloo", "Baker Street", "Hammersmith & City", 10},
    {"Baker Street", "Circle", "Baker Street", "Hammersmith & City", 10},
    {"Baker Street", "Jubilee", "Baker Street", "Hammersmith & City", 10},
    {"Baker Street", "Metropolitan", "Baker Street", "Hammersmith & City", 10},
    {"King's Cross St Pancras", "Circle", "King's Cross St Pancras", "Hammersmith & City", 10},
    {"King's Cross St Pancras", "Metropolitan", "King's Cross St Pancras", "Hammersmith & City", 10},
    {"King's Cross St Pancras", "Northern", "King's Cross St Pancras", "Hammersmith & City", 10},
    {"King's Cross St Pancras", "Piccadilly", "King's Cross St Pancras", "Hammersmith & City", 10},
    {"King's Cross St Pancras", "Victoria", "King's Cross St Pancras", "Hammersmith & City", 10},
    {"Farringdon", "Circle", "Farringdon", "Hammersmith & City", 10},
    {"Farringdon", "Metropolitan", "Farringdon", "Hammersmith & City", 10},
    {"Moorgate", "Circle", "Moorgate", "Hammersmith & City", 10},
    {"Moorgate", "Metropolitan", "Moorgate", "Hammersmith & City", 10},
    {"Moorgate", "Northern", "Moorgate", "Hammersmith & City", 10},
    {"Liverpool Street", "Central", "Liverpool Street", "Hammersmith & City", 10},
    {"Liverpool Street", "Circle", "Liverpool Street", "Hammersmith & City", 10},
    {"Liverpool Street", "London Overground", "Liverpool Street", "Hammersmith & City", 10},
    {"Liverpool Street", "Metropolitan", "Liverpool Street", "Hammersmith & City", 10},
    {"Liverpool Street", "TfL Rail", "Liverpool Street", "Hammersmith & City", 10},
    {"Aldgate East", "District", "Aldgate East", "Hammersmith & City", 10},
    {"Whitechapel", "District", "Whitechapel", "Hammersmith & City", 10},
    {"Whitechapel", "London Overground", "Whitechapel", "Hammersmith & City", 10},
    {"Mile End", "Central", "Mile End", "Hammersmith & City", 10},
    {"Mile End", "District", "Mile End", "Hammersmith & City", 10},
    {"Bow Church", "DLR", "Bow Road", "Hammersmith & City", 10},
    {"Bow Road", "District", "Bow Road", "Hammersmith & City", 10},
    {"Bromley-by-Bow", "District", "Bromley-by-Bow", "Hammersmith & City", 10},
    {"West Ham", "DLR", "West Ham", "Hammersmith & City", 10},
    {"West Ham", "District", "West Ham", "Hammersmith & City", 10},
    {"West Ham", "Jubilee", "West Ham", "Hammersmith & City", 10},
    {"Barking", "District", "Barking", "Hammersmith & City", 10},
    {"Barking", "London Overground", "Barking", "Hammersmith & City", 10},

    /* Transfers to stations on the Jubilee Line */
    {"Stratford", "Central", "Stratford", "Jubilee", 3},
    {"Stratford", "DLR", "Stratford", "Jubilee", 3},
    {"Stratford", "London Overground", "Stratford", "Jubilee", 3},
    {"Stratford", "TfL Rail", "Stratford", "Jubilee", 3},
    {"West Ham", "District", "West Ham", "Jubilee", 3},
    {"West Ham", "Hammersmith & City", "West Ham", "Jubilee", 3},
    {"Canning Town", "DLR", "Canning Town", "Jubilee", 3},
    {"Canary Wharf", "DLR", "Canary Wharf", "Jubilee", 2},
    {"Canada Water", "London Overground", "Canada Water", "Jubilee", 2},
    {"London Bridge", "Northern", "London Bridge", "Jubilee", 2},
    {"Waterloo", "Bakerloo", "Waterloo", "Jubilee", 3},
    {"Waterloo", "Northern", "Waterloo", "Jubilee", 3},
    {"Waterloo", "Waterloo & City", "Waterloo", "Jubilee", 3},
    {"Westminster", "Circle", "Westminster", "Jubilee", 2},
    {"Westminster", "District", "Westminster", "Jubilee", 2},
    {"Green Park", "Piccadilly", "Green Park", "Jubilee", 2},
    {"Green Park", "Victoria", "Green Park", "Jubilee", 2},
    {"Bond Street", "Central", "Bond Street", "Jubilee", 2},
    {"Baker Street", "Bakerloo", "Baker Street", "Jubilee", 3},
    {"Baker Street", "Circle", "Baker Street", "Jubilee", 3},
    {"Baker Street", "Hammersmith & City", "Baker Street", "Jubilee", 3},
    {"Baker Street", "Metropolitan", "Baker Street", "Jubilee", 3},
    {"Finchley Road", "Metropolitan", "Finchley Road", "Jubilee", 2},
    {"West Hampstead", "London Overground", "West Hampstead", "Jubilee", 2},
    {"Wembley Park", "Metropolitan", "Wembley Park", "Jubilee", 3},

    /* Transfers to stations on the Metropolitan Line */
    {"Uxbridge", "Piccadilly", "Uxbridge", "Metropolitan", 7},
    {"Hillingdon", "Piccadilly", "Hillingdon", "Metropolitan", 7},
    {"Rayners Lane", "Piccadilly", "Rayners Lane", "Metropolitan", 7},
    {"Wembley Park", "Jubilee", "Wembley Park", "Metropolitan", 4},
    {"Finchley Road", "Jubilee", "Finchley Road", "Metropolitan", 4},
    {"Baker Street", "Bakerloo", "Baker Street", "Metropolitan", 4},
    {"Baker Street", "Circle", "Baker Street", "Metropolitan", 4},
    {"Baker Street", "Hammersmith & City", "Baker Street", "Metropolitan", 4},
    {"Baker Street", "Jubilee", "Baker Street", "Metropolitan", 4},
    {"King's Cross St Pancras", "Circle", "King's Cross St Pancras", "Metropolitan", 5},
    {"King's Cross St Pancras", "Hammersmith & City", "King's Cross St Pancras", "Metropolitan", 5},
    {"King's Cross St Pancras", "Northern", "King's Cross St Pancras", "Metropolitan", 5},
    {"King's Cross St Pancras", "Piccadilly", "King's Cross St Pancras", "Metropolitan", 5},
    {"King's Cross St Pancras", "Victoria", "King's Cross St Pancras", "Metropolitan", 5},
    {"Farringdon", "Circle", "Farringdon", "Metropolitan", 5},
    {"Farringdon", "Hammersmith & City", "Farringdon", "Metropolitan", 5},
    {"Moorgate", "Circle", "Moorgate", "Metropolitan", 5},
    {"Moorgate", "Hammersmith & City", "Moorgate", "Metropolitan", 5},
    {"Moorgate", "Northern", "Moorgate", "Metropolitan", 5},
    {"Liverpool Street", "Central", "Liverpool Street", "Metropolitan", 5},
    {"Liverpool Street", "Circle", "Liverpool Street", "Metropolitan", 5},
    {"Liverpool Street", "London Overground", "Liverpool Street", "Metropolitan", 5},
    {"Liverpool Street", "Hammersmith & City", "Liverpool Street", "Metropolitan", 5},
    {"Liverpool Street", "TfL Rail", "Liverpool Street", "Metropolitan", 5},

    /* Transfers to stations on the Northern Line */
    {"Upper Holloway", "London Overground", "Archway", "Northern", 3},
    {"Euston", "London Overground", "Euston", "Northern", 2},
    {"Euston", "Victoria", "Euston", "Northern", 2},
    {"Warren Street", "Victoria", "Warren Street", "Northern", 3},
    {"Tottenham Court Road", "Central", "Tottenham Court Road", "Northern", 3},
    {"Leicester Square", "Piccadilly", "Leicester Square", "Northern", 3},
    {"Charing Cross", "Bakerloo", "Charing Cross", "Northern", 3},
    {"Embankment", "Circle", "Embankment", "Northern", 3},
    {"Embankment", "District", "Embankment", "Northern", 3},
    {"Waterloo", "Bakerloo", "Waterloo", "Northern", 3},
    {"Waterloo", "Jubilee", "Waterloo", "Northern", 3},
    {"Waterloo", "Waterloo & City", "Waterloo", "Northern", 3},
    {"King's Cross St Pancras", "Circle", "King's Cross St Pancras", "Northern", 3},
    {"King's Cross St Pancras", "Hammersmith & City", "King's Cross St Pancras", "Northern", 3},
    {"King's Cross St Pancras", "Metropolitan", "King's Cross St Pancras", "Northern", 3},
    {"King's Cross St Pancras", "Piccadilly", "King's Cross St Pancras", "Northern", 3},
    {"King's Cross St Pancras", "Victoria", "King's Cross St Pancras", "Northern", 3},
    {"Moorgate", "Circle", "Moorgate", "Northern", 3},
    {"Moorgate", "Hammersmith & City", "Moorgate", "Northern", 3},
    {"Moorgate", "Metropolitan", "Moorgate", "Northern", 3},
    {"Monument", "Circle", "Bank", "Northern", 3},
    {"Monument", "District", "Bank", "Northern", 3},
    {"Bank", "Central", "Bank", "Northern", 3},
    {"Bank", "DLR", "Bank", "Northern", 3},
    {"Bank", "Waterloo & City", "Bank", "Northern", 3},
    {"London Bridge", "Jubilee", "London Bridge", "Northern", 3},
    {"Elephant & Castle", "Bakerloo", "Elephant & Castle", "Northern", 3},
    {"Stockwell", "Victoria", "Stockwell", "Northern", 3},
    {"Clapham High Street", "London Overground", "Clapham North", "Northern", 3},

    /* Transfers to stations on the Piccadilly Line */
    {"Finsbury Park", "Victoria", "Finsbury Park", "Piccadilly", 3},
    {"King's Cross St Pancras", "Circle", "King's Cross St Pancras", "Piccadilly", 3},
    {"King's Cross St Pancras", "Hammersmith & City", "King's Cross St Pancras", "Piccadilly", 3},
    {"King's Cross St Pancras", "Metropolitan", "King's Cross St Pancras", "Piccadilly", 3},
    {"King's Cross St Pancras", "Northern", "King's Cross St Pancras", "Piccadilly", 3},
    {"King's Cross St Pancras", "Victoria", "King's Cross St Pancras", "Piccadilly", 3},
    {"Holborn", "Central", "Holborn", "Piccadilly", 3},
    {"Leicester Square", "Northern", "Leicester Square", "Piccadilly", 3},
    {"Piccadilly Circus", "Bakerloo", "Piccadilly Circus", "Piccadilly", 3},
    {"Green Park", "Jubilee", "Green Park", "Piccadilly", 3},
    {"Green Park", "Victoria", "Green Park", "Piccadilly", 3},
    {"South Kensington", "Circle", "South Kensington", "Piccadilly", 3},
    {"South Kensington", "District", "South Kensington", "Piccadilly", 3},
    {"Earl's Court", "District", "Earl's Court", "Piccadilly", 3},
    {"Hammersmith", "Circle", "Hammersmith", "Piccadilly", 3},
    {"Hammersmith", "District", "Hammersmith", "Piccadilly", 3},
    {"Hammersmith", "Hammersmith & City", "Hammersmith", "Piccadilly", 3},
    {"Acton Town", "District", "Acton Town", "Piccadilly", 3},
    {"Heathrow Terminal 4", "TfL Rail", "Heathrow Terminal 4", "Piccadilly", 5},
    {"Heathrow Terminals 2 & 3", "TfL Rail", "Heathrow Terminals 2 & 3", "Piccadilly", 5},
    {"Ealing Common", "District", "Ealing Common", "Piccadilly", 3},
    {"Rayners Lane", "Metropolitan", "Rayners Lane", "Piccadilly", 3},

    /* Transfers to stations on the Victoria Line */
    {"Stockwell", "Northern", "Stockwell", "Victoria", 2},
    {"Victoria", "Circle", "Victoria", "Victoria", 2},
    {"Victoria", "District", "Victoria", "Victoria", 2},
    {"Green Park", "Jubilee", "Green Park", "Victoria", 2},
    {"Green Park", "Piccadilly", "Green Park", "Victoria", 2},
    {"Oxford Circus", "Bakerloo", "Oxford Circus", "Victoria", 2},
    {"Oxford Circus", "Central", "Oxford Circus", "Victoria", 2},
    {"Warren Street", "Northern", "Warren Street", "Victoria", 2},
    {"Euston", "London Overground", "Euston", "Victoria", 2},
    {"Euston", "Northern", "Euston", "Victoria", 2},
    {"King's Cross St Pancras", "Circle", "King's Cross St Pancras", "Victoria", 2},
    {"King's Cross St Pancras", "Hammersmith & City", "King's Cross St Pancras", "Victoria", 2},
    {"King's Cross St Pancras", "Metropolitan", "King's Cross St Pancras", "Victoria", 2},
    {"King's Cross St Pancras", "Northern", "King's Cross St Pancras", "Victoria", 2},
    {"King's Cross St Pancras", "Piccadilly", "King's Cross St Pancras", "Victoria", 2},
    {"Highbury & Islington", "London Overground", "Highbury & Islington", "Victoria", 2},
    {"Finsbury Park", "Piccadilly", "Finsbury Park", "Victoria", 2},
    {"Seven Sisters", "London Overground", "Seven Sisters", "Victoria", 2},
    {"Blackhorse Road", "London Overground", "Blackhorse Road", "Victoria", 2},
    {"Walthamstow Central", "London Overground", "Walthamstow Central", "Victoria", 2},

    /* Transfers to stations on the Waterloo & City Line */
    {"Waterloo", "Bakerloo", "Waterloo", "Waterloo & City", 5},
    {"Waterloo", "Jubilee", "Waterloo", "Waterloo & City", 5},
    {"Waterloo", "Northern", "Waterloo", "Waterloo & City", 5},
    {"Monument", "Circle", "Bank", "Waterloo & City", 5},
    {"Monument", "District", "Bank", "Waterloo & City", 5},
    {"Bank", "Central", "Bank", "Waterloo & City", 5},
    {"Bank", "DLR", "Bank", "Waterloo & City", 5},
    {"Bank", "Northern", "Bank", "Waterloo & City", 5},

    /* Transfers to stations on the Docklands Light Railway (DLR) Line */
    {"Monument", "Circle", "Bank", "DLR", 3},
    {"Monument", "District", "Bank", "DLR", 3},
    {"Bank", "Central", "Bank", "DLR", 3},
    {"Bank", "Northern", "Bank", "DLR", 3},
    {"Bank", "Waterloo & City", "Bank", "DLR", 3},
    {"Tower Hill", "Circle", "Tower Gateway", "DLR", 10},
    {"Tower Hill", "District", "Tower Gateway", "DLR", 10},
    {"Shadwell", "London Overground", "Shadwell", "DLR", 2},
    {"Canary Wharf", "Jubilee", "Canary Wharf", "DLR", 3},
    {"Canning Town", "Jubilee", "Canning Town", "DLR", 3},
    {"Bow Road", "District", "Bow Church", "DLR", 10},
    {"West Ham", "District", "West Ham", "DLR", 10},
    {"West Ham", "Hammersmith & City", "West Ham", "DLR", 10},
    {"West Ham", "Jubilee", "West Ham", "DLR", 10},
    {"Stratford", "Central", "Stratford", "DLR", 5},
    {"Stratford", "Jubilee", "Stratford", "DLR", 5},
    {"Stratford", "London Overground", "Stratford", "DLR", 5},
    {"Stratford", "TfL Rail", "Stratford", "DLR", 5},

    /* Transfers to stations on the London Overground Line */
    {"Romford", "TfL Rail", "Romford", "London Overground", 30},
    {"Upminster", "District", "Upminster", "London Overground", 30},
    {"Liverpool Street", "Central", "Liverpool Street", "London Overground", 8},
    {"Liverpool Street", "Circle", "Liverpool Street", "London Overground", 8},
    {"Liverpool Street", "Hammersmith & City", "Liverpool Street", "London Overground", 8},
    {"Liverpool Street", "Metropolitan", "Liverpool Street", "London Overground", 8},
    {"Liverpool Street", "TfL Rail", "Liverpool Street", "London Overground", 8},
    {"Seven Sisters", "Victoria", "Seven Sisters", "London Overground", 15},
    {"Walthamstow Central", "Victoria", "Walthamstow Central", "London Overground", 15},
    {"Archway", "Northern", "Upper Holloway", "London Overground", 15},
    {"Blackhorse Road", "Victoria", "Blackhorse Road", "London Overground", 15},
    {"Forest Gate", "TfL Rail", "Wanstead Park", "London Overground", 15},
    {"Barking", "District", "Barking", "London Overground", 15},
    {"Barking", "Hammersmith & City", "Barking", "London Overground", 15},
    {"Harrow & Wealdstone", "Bakerloo", "Harrow & Wealdstone", "London Overground", 20},
    {"Wembley Central", "Bakerloo", "Wembley Central", "London Overground", 20},
    {"Willesden Junction", "Bakerloo", "Willesden Junction", "London Overground", 15},
    {"Queen's Park", "Bakerloo", "Queen's Park", "London Overground", 20},
    {"Euston", "Northern", "Euston", "London Overground", 20},
    {"Euston", "Victoria", "Euston", "London Overground", 20},
    {"Richmond", "District", "Richmond", "London Overground", 15},
    {"Kew Gardens", "District", "Kew Gardens", "London Overground", 15},
    {"Gunnersbury", "District", "Gunnersbury", "London Overground", 15},
    {"West Hampstead", "Jubilee", "West Hampstead", "London Overground", 8},
    {"Highbury & Islington", "Victoria", "Highbury & Islington", "London Overground", 5},
    {"Stratford", "Central", "Stratford", "London Overground", 8},
    {"Stratford", "DLR", "Stratford", "London Overground", 8},
    {"Stratford", "Jubilee", "Stratford", "London Overground", 8},
    {"Stratford", "TfL Rail", "Stratford", "London Overground", 8},
    {"West Brompton", "District", "West Brompton", "London Overground", 15},
    {"Shepherd's Bush", "Central", "Shepherd's Bush", "London Overground", 15},
    {"Whitechapel", "District", "Whitechapel", "London Overground", 4},
    {"Whitechapel", "Hammersmith & City", "Whitechapel", "London Overground", 4},
    {"Shadwell", "DLR", "Shadwell", "London Overground", 4},
    {"Canada Water", "Jubilee", "Canada Water", "London Overground", 4},
    {"West Croydon", "Tramlink", "West Croydon", "London Overground", 15},
    {"Clapham North", "Northern", "Clapham High Street", "London Overground", 15},

    /* Transfers to stations on the Transport for London (TfL) Rail Line */
    {"Heathrow Terminal 4", "Piccadilly", "Heathrow Terminal 4", "TfL Rail", 15},
    {"Heathrow Terminals 2 & 3", "Piccadilly", "Heathrow Terminals 2 & 3", "TfL Rail", 15},
    {"Ealing Broadway", "Central", "Ealing Broadway", "TfL Rail", 15},
    {"Ealing Broadway", "District", "Ealing Broadway", "TfL Rail", 15},
    {"Paddington", "Bakerloo", "Paddington", "TfL Rail", 15},
    {"Paddington", "Circle", "Paddington", "TfL Rail", 15},
    {"Paddington", "District", "Paddington", "TfL Rail", 15},
    {"Paddington", "Hammersmith & City", "Paddington", "TfL Rail", 15},
    {"Liverpool Street", "Central", "Liverpool Street", "TfL Rail", 10},
    {"Liverpool Street", "Circle", "Liverpool Street", "TfL Rail", 10},
    {"Liverpool Street", "Hammersmith & City", "Liverpool Street", "TfL Rail", 10},
    {"Liverpool Street", "London Overground", "Liverpool Street", "TfL Rail", 10},
    {"Liverpool Street", "Metropolitan", "Liverpool Street", "TfL Rail", 10},
    {"Stratford", "Central", "Stratford", "TfL Rail", 10},
    {"Stratford", "DLR", "Stratford", "TfL Rail", 10},
    {"Stratford", "Jubilee", "Stratford", "TfL Rail", 10},
    {"Stratford", "London Overground", "Stratford", "TfL Rail", 10},
    {"Wanstead Park", "London Overground", "Forest Gate", "TfL Rail", 10},
    {"Romford", "London Overground", "Romford", "TfL Rail", 10},

    /* Transfers to stations on the Tramlink Rail Line */
    {"Wimbledon", "District", "Wimbledon", "Tramlink", 5},
    {"West Croydon", "London Overground", "West Croydon", "Tramlink", 3}
};

#endif // TUBEPLANNER_H
